Repository Azure-Leap/NoBug, pull requests merged in 2023-05, with the labels that each got.

#37 Login form
  fe/components/auth/logIn.tsx
  fe/components/auth/signIn.tsx
  fe/components/auth/signUp.tsx
  fe/components/auth/styles.module.css
  fe/package-lock.json
  fe/package.json
  fe/pages/_document.tsx
Labels: Frontend, page

#39 "hereglegch nevterch burtguuldeg bolloo"
  be/app.ts
  be/controller/auth.ts
  be/model/freelancer.ts
  be/model/user.ts
  be/package-lock.json
  be/package.json
  be/routes/auth.ts
  fe/context/userContext.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/auth/logIn.tsx
  fe/pages/auth/signIn.tsx
  fe/pages/auth/signUp.tsx
  fe/pages/auth/styles.module.css
Labels: Backend, Frontend

#40 cloudinary luu image hadgaldag bolloo
  be/app.ts
  be/controller/freelancer.ts
  be/model/freelancer.ts
  be/package-lock.json
  be/package.json
  be/utils/cloudinary.ts
Labels: Backend

#42 Hero style
  fe/components/category.tsx
  fe/components/hero section/hero.tsx
  fe/components/hero section/slider.tsx
  fe/next.config.js
  fe/package-lock.json
  fe/package.json
  fe/pages/index.tsx
  fe/public/back.jpg
  fe/public/pexels-andreea-ch-1166643.jpg
Labels: Frontend

#44 Chat design
  .DS_Store
  fe/components/Chat/main/bottom.tsx
  fe/components/Chat/main/index.tsx
  fe/components/Chat/main/mainChat/mainChat.tsx
  fe/components/Chat/main/mainChat/oneChat.tsx
  fe/components/Chat/main/top.tsx
  fe/components/Chat/sidebar/AllMessage.tsx
  fe/components/Chat/sidebar/OneMessage.tsx
  fe/components/Chat/sidebar/index.tsx
  fe/components/Chat/sidebar/search.tsx
  fe/context/chatContext.tsx
  fe/context/userContext.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/chat.tsx
  fe/styles/globals.css
  package-lock.json
Labels: Frontend, page

#45 service freelancer populate
  be/controller/freelancer.ts
  be/controller/service.ts
  be/model/freelancer.ts
  be/model/services.ts
Labels: Backend

#46 category data nemev
  fe/components/category.tsx
  fe/components/navbar/drawer.tsx
  fe/components/navbar/navbar.tsx
  fe/components/navbar/nestedlist.tsx
Labels: documentation

#47 category be data nemev
  .DS_Store
  be/.DS_Store
  be/controller/category.ts
  be/model/categories.ts
  fe/components/category.tsx
  fe/components/profiledrawer/profiledrawer.tsx
  fe/components/profiledrawer/profilelist.tsx
  fe/context/categoryContext.tsx
  fe/pages/_app.tsx
  fe/pages/index.tsx
Labels: Backend

#48 mobile-responvie-cat
  .DS_Store
  .gitignore
  be/.DS_Store
  fe/components/category.tsx
  fe/components/mobileCat.tsx
  fe/components/navbar/navbar.tsx
Labels: Frontend

#50 Upload image
  .gitignore
  be/controller/auth.ts
  be/controller/freelancer.ts
  be/model/user.ts
  be/routes/auth.ts
  be/utils/confirmation.ts
  be/utils/sendEmail.ts
  fe/components/category.tsx
  fe/components/expertFreelander.tsx
  fe/components/footer.tsx
  fe/components/popularCat.tsx
  fe/components/profile/portfolio/portfolio.tsx
  fe/components/profile/portfolio/portfolioModal.tsx
  fe/components/profile/profileCard.tsx
  fe/components/profile/profileImageModal/chooseFile.tsx
  fe/components/profile/profileImageModal/profileImageModal.tsx
  fe/components/profile/profileImageModal/uploadProfileImage.tsx
  fe/components/profile/skills.tsx
  fe/context/profileContext.tsx
  fe/context/uploadContext.tsx
  fe/interfaces/interfaces.ts
  fe/package-lock.json
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/auth/signUp.tsx
  fe/pages/home.tsx
  fe/pages/index.tsx
  fe/pages/profile/[id].tsx
Labels: Frontend, component

#51 style oorchlov
  fe/components/category.tsx
  fe/components/hero section/hero.tsx
  fe/components/navbar/drawer.tsx
  fe/components/navbar/navbar.tsx
  fe/components/navbar/nestedlist.tsx
  fe/public/back11.webp
  fe/public/back111.webp
  fe/public/back3.jpeg
  fe/public/back4.jpeg
Labels: Frontend

#52 Upload image
  be/app.ts
  be/controller/freelancer.ts
  be/controller/user.ts
  be/routes/user.ts
  fe/components/Chat/main/mainChat/mainChat.tsx
  fe/components/Chat/main/mainChat/oneChat.tsx
  fe/components/expertFreelander.tsx
  fe/components/layout.tsx
  fe/components/loading.tsx
  fe/components/profile/profileCard/editProfile.tsx
  fe/components/profile/profileCard/editProfileModal.tsx
  fe/components/profile/profileCard/profileCard.tsx
  fe/components/profile/profileImageModal/chooseFile.tsx
  fe/components/profile/profileImageModal/profileImageModal.tsx
  fe/components/profile/profileImageModal/uploadProfileImage.tsx
  fe/context/loadingContext.tsx
  fe/context/userContext.tsx
  fe/next.config.js
  fe/package-lock.json
  fe/package.json
  fe/pages/_app.tsx
  fe/pages/index.tsx
  fe/pages/profile/[id].tsx
  fe/styles/globals.css
  fe/variables.tsx
Labels: Backend, Frontend

#53 Post moment
  .DS_Store
  fe/components/navbar/navbar.tsx
  fe/context/categoryContext.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/index.tsx
  fe/pages/postmoment.tsx
  fe/variables.tsx
Labels: Frontend, component

#55 admin dashboard ytunhii design gargalaa profile iin design iig zaslaa
  be/app.ts
  be/controller/freelancer.ts
  be/controller/portfolio.ts
  be/controller/service.ts
  be/middlewares/error.ts
  be/model/services.ts
  be/model/user.ts
  be/routes/portfolio.ts
  be/routes/service.ts
  fe/components/adminPage/chart/chart.tsx
  fe/components/cards/catCard.tsx
  fe/components/cards/freelancerCard.tsx
  fe/components/cards/offerCard.tsx
  fe/components/expertFreelander.tsx
  fe/components/freelancers.tsx
  fe/components/modal/addPortfolio.tsx
  fe/components/modal/editProfile.tsx
  fe/components/modal/portfolio.tsx
  fe/components/offers.tsx
  fe/components/popularCat.tsx
  fe/components/profile/offers.tsx
  fe/components/profile/portfolio/portfolio.tsx
  fe/components/profile/profileCard/editProfile.tsx
  fe/components/profile/profileCard/profileCard.tsx
  fe/components/profile/sideBar.tsx
  fe/next.config.js
  fe/pages/admin.tsx
  fe/pages/index.tsx
  fe/pages/offer/[id].tsx
  fe/pages/profile/[id].tsx
Labels: Frontend

#56 Filter page
  fe/components/freelaancersPage/freelancerHeader.tsx
  fe/components/freelaancersPage/freelancerSearchBar.tsx
  fe/components/freelaancersPage/freelancersBody.tsx
  fe/components/freelaancersPage/sideBarFilter.module.css
  fe/components/freelaancersPage/sidebarfilter.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/freelancers.tsx
Labels: Backend, Frontend, page

#57 freelancer iig detail burtgej avah page ajilgaatai bolloo
  be/controller/freelancer.ts
  be/model/user.ts
  fe/.gitignore
  fe/components/adminPage/chart/chart.tsx
  fe/components/cards/offerCard.tsx
  fe/components/freelancersPage/freelancerHeader.tsx
  fe/components/freelancersPage/freelancerSearchBar.tsx
  fe/components/freelancersPage/freelancersBody.tsx
  fe/components/freelancersPage/sideBarFilter.module.css
  fe/components/freelancersPage/sidebarfilter.tsx
  fe/components/navbar/navbar.tsx
  fe/components/profile/portfolio/portfolio.tsx
  fe/components/profile/profileCard/profileCard.tsx
  fe/components/profile/sideBar.tsx
  fe/components/toTop.tsx
  fe/context/modalContext.tsx
  fe/data/data.tsx
  fe/modal/ReadMoreModal.tsx
  fe/modal/addPortfolio.tsx
  fe/modal/editProfile.tsx
  fe/modal/modal.tsx
  fe/modal/portfolio.tsx
  fe/modal/profileImageModal.tsx
  fe/pages/freelancerForm.tsx
  fe/pages/freelancers.tsx
  fe/pages/index.tsx
  fe/pages/profile/[id].tsx
Labels: Backend, Frontend

#58 payment deer qr code gargaj irlee
  be/app.ts
  be/controller/portfolio.ts
  be/controller/qr.ts
  be/package-lock.json
  be/package.json
  be/routes/qr.ts
  fe/components/cards/freelancerCard.tsx
  fe/components/cards/offerCard.tsx
  fe/components/profile/portfolio/portfolio.tsx
  fe/components/profile/skills.tsx
  fe/context/categoryContext.tsx
  fe/modal/addPortfolio.tsx
  fe/modal/portfolio.tsx
  fe/pages/payment.tsx
  fe/pages/profile/[id].tsx
Labels: bug, Frontend, component

#59 post moment page fe stated hadgaldag bolov
  fe/package-lock.json
  fe/package.json
  fe/pages/postmoment.tsx
Labels: Frontend
