Repository Azure-Leap/NoBug, pull requests merged in 2023-04, with the labels that each got.

#19 Footer
  fe/package-lock.json
  fe/package.json
  fe/pages/footer.tsx
Labels: component

#20 Service crud
  be/app.ts
  be/controller/service.ts
  be/model/client.ts
  be/model/services.ts
  be/routes/service.ts
Labels: Backend, API

#21 Freelancer crud
  be/app.ts
  be/controller/freelancer.ts
  be/middlewares/error.ts
  be/model/freelancer.ts
  be/routes/freelancer.ts
Labels: Backend, API

#22 Category CRUD hiilee
  be/app.ts
  be/controller/category.ts
  be/model/categories.ts
  be/model/freelancer.ts
  be/routes/category.ts
Labels: Backend, API

#23 expert freelancer v2
  fe/components/expertFreelander.tsx
  fe/styles/globals.css
Labels: Frontend, component

#24 Navbar
  fe/components/navbar/drawer.tsx
  fe/components/navbar/navbar.tsx
  fe/package-lock.json
  fe/package.json
Labels: component

#25 Navbar
  .DS_Store
  fe/components/navbar/drawer.tsx
  fe/components/navbar/navbar.tsx
  fe/pages/index.tsx
  fe/public/asd.png
  fe/public/logo2.png
Labels: Frontend, component

#26 Commend part
  fe/components/commendPart.tsx
Labels: Frontend, component

#28 neg card nii designiig uurchluv
  be/controller/freelancer.ts
  be/model/freelancer.ts
  be/package.json
  be/routes/freelancer.ts
  fe/components/expertFreelander.tsx
  fe/components/navbar/navbar.tsx
  fe/package-lock.json
  fe/package.json
  fe/pages/index.tsx
Labels: Frontend, component

#35 profile page iin yrunhii designiig gargalaa
  fe/components/commendPart.tsx
  fe/components/expertFreelander.tsx
  fe/components/footer.tsx
  fe/components/layout.tsx
  fe/components/navbar/navbar.tsx
  fe/components/offerCard.tsx
  fe/components/popularCat.tsx
  fe/components/profile/ReadMoreModal.tsx
  fe/components/profile/offers.tsx
  fe/components/profile/portfolio/portfolio.tsx
  fe/components/profile/portfolio/portfolioModal.tsx
  fe/components/profile/profileCard.tsx
  fe/components/profile/sideBar.tsx
  fe/components/profile/skills.tsx
  fe/next.config.js
  fe/pages/_app.tsx
  fe/pages/index.tsx
  fe/pages/profile/[id].tsx
Labels: Frontend, page

#36 profile page iig responsive bolgoloo
  fe/components/offerCard.tsx
  fe/components/profile/ReadMoreModal.tsx
  fe/components/profile/offers.tsx
  fe/components/profile/portfolio/portfolio.tsx
  fe/components/profile/portfolio/portfolioModal.tsx
  fe/components/profile/profileCard.tsx
  fe/components/profile/sideBar.tsx
  fe/components/profile/skills.tsx
  fe/pages/profile/[id].tsx
Labels: Frontend, page
